simple-backend:
  port:
    container: 8080
    external: 8080
  image:
    name: romanowalex/simple-backend
    version: v1.0
  enviroments:
    SPRING_PROFILES_ACTIVE: docker

simple-frontend:
  ingress:
    enabled: true
  port:
    container: 80
    external: 3000
  image:
    name: romanowalex/simple-frontend
    version: v1.0