port: 5432

image:
  name: postgres
  version: 13

database:
  default:
    name: postgres
    user: postgres
    password: postgres
  main:
    name: simple_backend
    user: program
    password: test